---
- name: My Test Playbook
  hosts: webservers
  become: true
  tasks:
  - name: Create user
    user: name='{{item}}' state=present
    with_items:
        - Sai
        - Raj
        - Hari     
      
